services:
    app:
        user: "www-data:www-data"
        build: .
        container_name: blog_app
        volumes:
            - .:/var/www
        depends_on:
            - mysql

        command: >
            sh -c "chown -R www-data:www-data /var/www/storage /var/www/public/storage &&
                   chmod -R 775 /var/www/storage /var/www/public/storage &&
                   php-fpm"

    nginx:
        image: nginx:latest
        container_name: blog_nginx
        ports:
            - "8181:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: blog_mysql
        restart: always
        environment:
            MYSQL_DATABASE: blog_dashboard
            MYSQL_USER: younes
            MYSQL_PASSWORD: Blog81Dashboard
            MYSQL_ROOT_PASSWORD: rootpass
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
